lr=0.0001           # Learning rate
max_epoch=100       # Max epoch
dropout_rate=0.5    # Dropout rate
target_delay=5      # Target delay of LSTM
num_layers=3        # The number of layers of LSTM
cell_size=256       # LSTM cell size
seq_len=20          # Sequence length
num_batches=200     # The number of batches
                    # Note that batch_size=seq_len*num_batches
